name: solar-system
on:
  workflow_dispatch:
  push:
    branches:
    - main
    - 'feature/*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: checkout stage 
        uses: checkout@v7
      
      - name: setting up node jss
        uses: actions/setup-node@v7
        with:
          node-version: 24

      - name: installing dependency 
        run: npm install
      
      - name: tesing the node app
        run: npm test 
      
      - name: installing coverage report
        run: npm run coverage